// Generated by Wrangler
// After running `pnpm cf-typegen`, update the interface below
// with your actual bindings from wrangler.jsonc

declare global {
  interface CloudflareEnv {
    DB: D1Database;
    R2_BUCKET: R2Bucket;
    AI: Ai;
    AI_GATEWAY_ID?: string;
    AI_GATEWAY_ACCOUNT_ID?: string;
    OPENAI_API_KEY?: string;
    NEXT_PUBLIC_APP_NAME?: string;
    WORKER_SELF_REFERENCE?: Fetcher;
    ASSETS?: Fetcher;
  }
}

export {};
